#!/bin/bash

PKG_NAME=$(basename "$SYNOPKG_PKGDEST")
PKG_DEST="$SYNOPKG_PKGDEST"

status() {
    if [ -f "${PKG_DEST}/ui/index.html" ]; then
        exit 0
    else
        exit 1
    fi
}

case "$1" in
    start)   exit 0  ;;
    stop)    exit 0  ;;
    restart) exit 0  ;;
    status)  status  ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 2
        ;;
esac
exit 0
