location ^~ /webman/3rdparty/LibreSpeedTest/backend/empty.cgi {
    return 200 "OK";
}

location ^~ /webman/3rdparty/LibreSpeedTest/backend/garbage.cgi {
    alias /var/packages/LibreSpeedTest/target/ui/backend/garbage.bin;
    add_header Content-Type application/octet-stream;
    add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
}
